// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkBabyData.Models;

public partial class Order
{
    public Guid OrderId { get; set; }

    public Guid? CustomerId { get; set; }

    public DateOnly? OrderDate { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Voucher { get; set; }

    public string OrderStatus { get; set; }

    public string OrderShippingAddress { get; set; }

    public string OrderBillingAddress { get; set; }

    public string OrderPaymentMethod { get; set; }

    public string OrderShippingMethod { get; set; }

    public string OrderTrackingNumber { get; set; }

    public DateOnly? OrderCreatedDate { get; set; }

    public DateOnly? OrderUpdatedDate { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}