// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkBabyData.Models;

public partial class Review
{
    public Guid ReviewId { get; set; }

    public Guid? ProductId { get; set; }

    public Guid? CustomerId { get; set; }

    public int? Rating { get; set; }

    public string ReviewText { get; set; }

    public string ReviewImg { get; set; }

    public string ReviewTitle { get; set; }

    public int? ReviewHelpfulCount { get; set; }

    public int? ReviewNotHelpfulCount { get; set; }

    public DateOnly? ReviewCreatedDate { get; set; }

    public DateOnly? ReviewUpdatedDate { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Product Product { get; set; }
}