// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkBabyData.Models;

public partial class Vendor
{
    public Guid VendorId { get; set; }

    public string VendorName { get; set; }

    public string VendorAddress { get; set; }

    public string VendorPhone { get; set; }

    public string VendorEmail { get; set; }

    public string VendorContactPerson { get; set; }

    public string VendorWebsite { get; set; }

    public bool? VendorStatus { get; set; }

    public DateOnly? VendorCreatedDate { get; set; }

    public DateOnly? VendorUpdatedDate { get; set; }

    public string VendorNotes { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}